export const ANALYTICS_EVENT_NAMES = [
  "USER_INVITED",
  "USER_LOGGED_IN",
  "ONBOARDING_COMPLETED",
  "AREA_SELECTED",
  "TODAY_VIEWED",
  "ITEM_MARKED_LEARNED",
  "RATING_SUBMITTED",
  "REPORT_SUBMITTED",
  "SOURCE_LINK_CLICKED",
  "DASHBOARD_VIEWED",
  "ADMIN_USER_CREATED",
  "ADMIN_AREA_CREATED",
  "ADMIN_SUBJECT_OVERRIDDEN",
  "REPORT_RESOLVED",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];
