apiVersion: v1
kind: Service
metadata:
  name: narau-app
  namespace: app-narau
  labels:
    app: narau-app
spec:
  selector:
    app: narau-app
  type: LoadBalancer
  ports:
    - port: 3030
      name: http
      targetPort: 3030
      protocol: TCP
